---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1567986/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R img.projects $DEPLOYPATH
